### ISSUE TITLE
read/write access for new contributor

### ISSUE THREAD

**Issue by jawntehrani** [maptime/philadelphia#8]
@geografa please provide Daniel Beck (https://github.com/ddbeck) access to editing the contents of this repository. thank you!

**Comment by jawntehrani** [comment]
on a quasi-related note, is it possible (without deleting and re-creating the repo) to start with a fresh clone/fork of the chapter website template?

**Comment by geografa** [comment]
@ddbeck is in. 

> on a quasi-related note, is it possible (without deleting and re-creating the repo) to start with a fresh clone/fork of the chapter website template?

@jawntehrani Not sure I understand. What's the issue with your current repo/site? You can blow away the contents and just repost stuff like your _posts and images. Any custom stuff like js or css you'd need to figure out as well.

**Comment by jawntehrani** [comment]
@geografa essentially it's been months since we've touched the site, and ideally what I'd like to do is just start fresh. So while I could go in and manually delete the old posts/clean up the source code, I didn't know if there was an option which would re-store the repo to where it was when we received it day one, and then move forward with "2.0" from there. Sorry for not phrasing/explaining that more clearly earlier.

**Comment by ddbeck** [comment]
@geografa Thanks for granting me access! (Also, I think we met at the Write the Docs conference last year. Small world.)

@jawntehrani If I understand you correctly, then I think we can revert the commits that added the existing posts and go from there. It *should* be easy (not exactly a reset button, but close enough). If you want to learn how that's done, let me know.

If that's all, I think this issue can be closed.

**Comment by jawntehrani** [comment]
cool, works for me. thank you @geografa @ddbeck !!
